<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->
<template>
  <el-form
    :model="formData"
    ref="vForm"
    :rules="rules"
    label-position="left"
    label-width="80px"
    size="default"
    @submit.prevent
  >
    <div class="card-container">
      <el-card
        style="
           {
            width: 100% !important;
          }
        "
        shadow="never"
      >
        <template #header>
          <div class="clear-fix">
            <span class="title_login">欢迎来到英雄联盟</span>
          </div>
        </template>
        <el-row>
          <el-col :span="24" class="grid-cell">
            <el-form-item
              label=""
              label-width="0"
              prop="input62943"
              class="required"
            >
              <el-input
                v-model="formData.input62943"
                type="text"
                placeholder="邮箱"
              ></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24" class="grid-cell">
            <el-form-item
              label=""
              label-width="0"
              prop="input32404"
              class="required"
            >
              <el-input
                v-model="formData.input32404"
                type="password"
                :show-password="true"
                placeholder="密码"
                :minlength="6"
                :maxlength="16"
              ></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :md="12" :sm="12" :xs="12" class="grid-cell">
            <div class="static-content-item">
              <el-button class="login">登录</el-button>
            </div>
          </el-col>
          <el-col :md="12" :sm="12" :xs="12" class="grid-cell">
            <div class="static-content-item">
              <el-button class="zhuce">注册</el-button>
            </div>
          </el-col>
        </el-row>
      </el-card>
    </div>
  </el-form>
</template>

<script>
import { defineComponent, toRefs, reactive, getCurrentInstance } from "vue";
export default defineComponent({
  components: {},
  props: {},
  setup() {
    const state = reactive({
      formData: {
        input62943: "",
        input32404: "",
      },
      rules: {
        input62943: [
          {
            required: true,
            message: "字段值不可为空",
          },
          {
            pattern: /^([-_A-Za-z0-9.]+)@([_A-Za-z0-9]+\.)+[A-Za-z0-9]{2,3}$/,
            trigger: ["blur", "change"],
            message: "昵称不能为空",
          },
        ],
        input32404: [
          {
            required: true,
            message: "字段值不可为空",
          },
        ],
      },
    });
    const instance = getCurrentInstance();
    const submitForm = () => {
      instance.ctx.$refs["vForm"].validate((valid) => {
        if (!valid) return;
        //TODO: 提交表单
      });
    };
    const resetForm = () => {
      instance.ctx.$refs["vForm"].resetFields();
    };
    return {
      ...toRefs(state),
      submitForm,
      resetForm,
    };
  },
});
</script>

<style lang="scss">
.login {
  width: 95px;
}

.zhuce {
  width: 95px;
}

.title_login {
  margin-left: 36px;
}

.el-input-number.full-width-input,
.el-cascader.full-width-input {
  width: 100% !important;
}

.el-form-item--medium {
  .el-radio {
    line-height: 36px !important;
  }

  .el-rate {
    margin-top: 8px;
  }
}

.el-form-item--small {
  .el-radio {
    line-height: 32px !important;
  }

  .el-rate {
    margin-top: 6px;
  }
}

.el-form-item--mini {
  .el-radio {
    line-height: 28px !important;
  }

  .el-rate {
    margin-top: 4px;
  }
}

.clear-fix:before,
.clear-fix:after {
  display: table;
  content: "";
}

.clear-fix:after {
  clear: both;
}

.float-right {
  float: right;
}
</style>

<style lang="scss" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

.label-left-align :deep(.el-form-item__label) {
  text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
  text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
  text-align: right;
}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  :deep(.el-divider--horizontal) {
    margin: 0;
  }
}
</style>
