<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form
    :model="formData"
    ref="vForm"
    :rules="rules"
    label-position="top"
    label-width="70px"
    size="default"
    @submit.prevent
  >
    <el-form-item label="email" prop="input115957" class="label-center-align">
      <el-input v-model="formData.input115957" type="text" clearable></el-input>
    </el-form-item>
    <el-form-item label="passw" prop="input50141" class="label-center-align">
      <el-input
        v-model="formData.input50141"
        type="password"
        clearable
        :minlength="6"
        :maxlength="16"
      >
      </el-input>
    </el-form-item>
    <div class="static-content-item">
      <el-button>button</el-button>
    </div>
    <div class="static-content-item">
      <el-button>button</el-button>
    </div>
  </el-form>
</template>

<script>
import { defineComponent, toRefs, reactive, getCurrentInstance } from "vue";
export default defineComponent({
  components: {},
  props: {},
  setup() {
    const state = reactive({
      formData: {
        input115957: "",
        input50141: "",
      },
      rules: {
        input115957: [
          {
            pattern: /^([-_A-Za-z0-9.]+)@([_A-Za-z0-9]+\.)+[A-Za-z0-9]{2,3}$/,
            trigger: ["blur", "change"],
            message: "请输入正确邮箱",
          },
        ],
      },
    });
    const instance = getCurrentInstance();
    const submitForm = () => {
      instance.ctx.$refs["vForm"].validate((valid) => {
        if (!valid) return;
        //TODO: 提交表单
      });
    };
    const resetForm = () => {
      instance.ctx.$refs["vForm"].resetFields();
    };
    return {
      ...toRefs(state),
      submitForm,
      resetForm,
    };
  },
});
</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
  width: 100% !important;
}

.el-form-item--medium {
  .el-radio {
    line-height: 36px !important;
  }

  .el-rate {
    margin-top: 8px;
  }
}

.el-form-item--small {
  .el-radio {
    line-height: 32px !important;
  }

  .el-rate {
    margin-top: 6px;
  }
}

.el-form-item--mini {
  .el-radio {
    line-height: 28px !important;
  }

  .el-rate {
    margin-top: 4px;
  }
}

.clear-fix:before,
.clear-fix:after {
  display: table;
  content: "";
}

.clear-fix:after {
  clear: both;
}

.float-right {
  float: right;
}
</style>

<style lang="scss" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

.label-left-align :deep(.el-form-item__label) {
  text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
  text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
  text-align: right;
}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  :deep(.el-divider--horizontal) {
    margin: 0;
  }
}
</style>
